### ISSUE TITLE
0.0.1发现

### ISSUE THREAD

**Issue by LIPiston** [ResetPower/Epherome#1]
1.目前的javaw路径需自行填写
**2.无法启动特殊端（如optifine端**
_3.档案的版本填写应为json文件名填写_
4.下载游戏
5.版本隔离的识别
6.界面可以做得更整齐美观

**Comment by 1910093789** [comment]
1.目前的javaw路径需自行填写
**2.无法启动特殊端（如optifine端**
_3.档案的版本填写应为json文件名填写_
4.下载游戏
5.版本隔离的识别

**Comment by ResetPower** [comment]
1: 将会在0.0.2检测系统环境变量JAVA_PATH，检测不到就询问用户并提示下载
2: 将会在0.0.2提供forge, liteloader, fabric, optifine的支持
3: 这可能有一定困难，且我们的json路径格式为 <文件夹>/versions/<版本>/<版本>.json ，jar路径格式为<文件夹>/versions/<版本>/<版本>.jar 如果这样我们是不是还要填写jar文件名呢？是不是还要填写文件夹名呢？版本文件夹与json文件名与jar文件名一致是Minecraft约定俗成的规则。
4: 将会在0.0.2或0.0.3提供支持
5: 将会在0.0.2提供支持

**Comment by 1910093789** [comment]
第三点我认为得给予明确的提示，否则遇到类似'1.12.2-optifine_G5.json'一类的文件会无法启动

**Comment by Infinity-Energy** [comment]
3.我似乎可以不写.json，或者是填写的时候不用带上“.json”？

**Comment by Infinity-Energy** [comment]
![image](https://user-images.githubusercontent.com/59878199/108139856-ec63d580-70fb-11eb-9066-b19f09a7cba1.png)

**Comment by LIPiston** [comment]
版本选择填写的是JSON的文件名，不包括后缀

**Comment by ResetPower** [comment]
@LIPiston 界面更整齐美观指的是主页两个卡片不对齐嘛……

**Comment by Infinity-Energy** [comment]
那我认为可以自动检测json? @LIPiston @ResetPower

**Comment by ResetPower** [comment]
> 那我认为可以自动检测json? @LIPiston @ResetPower 

OK

**Comment by ResetPower** [comment]
将在0.0.3中全部实现
