### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Pantyhose-X** [ResetPower/Epherome#10]
我的世界地图转换成 [minetest](https://www.minetest.net) https://minetest.cosoc.cn/t/minecraft-minetest-windows-10/292

获利方法
https://www.bountysource.com/
https://afdian.net/

**Comment by ResetPower** [comment]
roger that!
因为各种原因准备在epherome中放弃vue框架，所以可能需要ui部分重构，在0.0.2版本发布之后这个功能将会被我加入to-do list的！

**Comment by LIPiston** [comment]
一点点建议，时不时会来干你的
--------
- 首先下载功能得先做完
- 设置界面的切换动画生硬
- 制作导入导出整合包功能
- 可视化更改options.txt
-  一言不需要这么频繁的刷新
- 可以将jvm启动项丢出来
- 可以将启动脚本导出（方便出门u盘冲mc

**Comment by ResetPower** [comment]
来自 @LIPiston 的建议，我抄一下原文：
> 1. 首先下载功能得先做完
> 2. 设置界面的切换动画生硬
> 3. 制作导入导出整合包功能
> 4. 可视化更改options.txt
> 5. 一言不需要这么频繁的刷新
> 6. 可以将jvm启动项丢出来
> 7. 可以将启动脚本导出（方便出门u盘冲mc

1. 0.0.4一定（
2. 如果指左侧Tab栏的话，我可以告诉你那里根本没动画…… 0.0.4一定（
3. 0.0.4或者0.0.5一定（
4. 0.0.4一定
5. 这个是 React 状态保存的问题，如果能解决的话我0.0.4一定改
6. 0.0.4一定
7. 0.0.4一定

**Comment by Pantyhose-X** [comment]
@ResetPower 如果你不能从Epherome项目获利，我建议你放弃这个项目。
* 我建议你开发自己的像素游戏
* 基于开源的[Voxel Tools](https://voxel-tools.readthedocs.io/en/latest/index.html)
* [Seed of Andromeda](https://github.com/RegrowthStudios/SoACode-Public) 
* [Minetest](https://github.com/minetest/minetest)
* [C++ voxel](https://github.com/mgerhardy/engine)

**Comment by ResetPower** [comment]
抱歉。获利并不是重要的目的，因此我不会放弃 Epherome 项目。

**Comment by Pantyhose-X** [comment]
> 抱歉。获利并不是重要的目的，因此我不会放弃 Epherome 项目。

开发自己的像素游戏,不好吗

**Comment by LIPiston** [comment]
0.0.5的发现
---

"扩展"and"进程管理"中的文字在dark模式下能要你眼睛的命

**Comment by ResetPower** [comment]
> ## 0.0.5的发现
> "扩展"and"进程管理"中的文字在dark模式下能要你眼睛的命

Fixed in the latest commit.

**Comment by ResetPower** [comment]
finished.
