### ISSUE TITLE
群组: 添加

### ISSUE THREAD

**Issue by Pantyhose-X** [ResetPower/Epherome#112]
请创建一个群组在https://rvlt.gg/ 它是discord的开源替代品, 它不需要vpn翻墙

**Comment by ResetPower** [comment]
For those who can't cross the Chinese Great Fire Wall, we recommend them to join our Tencent QQ Group.

**Comment by ResetPower** [comment]
For group number see https://epherome.com/about

**Comment by Pantyhose-X** [comment]
> For group number see https://epherome.com/about

We value privacy and don't like software like QQ that gets users' privacy

**Comment by ResetPower** [comment]
> > For group number see https://epherome.com/about
> 
> We value privacy and don't like software like QQ that gets users' privacy

You can't value privacy without crossing the Great Firewall
