### ISSUE TITLE
epherome官网验证服务寄啦~

### ISSUE THREAD

**Issue by mc-doge666** [ResetPower/Epherome#118]
![image](https://github.com/ResetPower/Epherome/assets/77102592/c734dd90-f204-4be2-a4c6-4e0884e04d48)
![image](https://github.com/ResetPower/Epherome/assets/77102592/61504d3d-1947-4818-a137-30f7183c1e63)

**Comment by ResetPower** [comment]
Yes. Epherome's authentication server is down. That's not permanent, since Epherome account don't have any use in the foreseeable future.
