### ISSUE TITLE
Debugging bug about npm run tauri dev.

### ISSUE THREAD

**Issue by SpiderKingWynn** [ResetPower/Epherome#140]
The `top-level await` is not supported by **older web browser**, so the following bug occurs when debugging with `npm run tauri dev`:
```
[Error] SyntaxError: Unexpected identifier 'app'. Expected ';' after variable declaration.
    promiseReactionJob
```
Test environment: **macOS 11.7.10**
Please resolve this issue as soon as possible.

**Comment by ResetPower** [comment]
Resolve in the latest commit.
