### ISSUE TITLE
A bug in the Settings Page - Download Source drop-down box appears

### ISSUE THREAD

**Issue by SpiderKingWynn** [ResetPower/Epherome#147]
*~Ahhhhh why are there so many bugs in the new version as soon as it's released ahhhhhhhhhhhhhhhhhhhhhhhhhhh~*
⬆️ The above was written by SpiderKingWynn during a psychotic episode

---

**Description of the problem:** When entering the Download interface of Settings and switching the download source, there is a bug that **the description will not be changed immediately after clicking it**, and you can only switch the page manually to update the status.

Please resolve this **LITTLE BUG** as quickly as possible rather than delaying it for **THREE DAYS**.

**T.H.A.N.K.S!**

**Comment by ResetPower** [comment]
Fixed.
