### ISSUE TITLE
[Feature Request] 一些建议和问题

### ISSUE THREAD

**Issue by alex3236** [ResetPower/Epherome#20]
## 问题
1. 在启动器百花齐放的时代，准备做什么特色功能来脱颖而出？
2. 有没有打算打通在线服务？
如果只是练手用 就当我没说

**Comment by eagle3236** [comment]
## 建议
1. 完善基本功能
2. 建议重新设计 UI
3. 可自定义的主界面，供整合包作者使用
4. 可换源的下载服务，参考 HMCL
5. 用 curseforge API 打通 mod 下载服务

**Comment by ResetPower** [comment]
关于 UI，有没有具体的重新设计建议呢？

**Comment by ResetPower** [comment]
> ## 问题
> 1. 在启动器百花齐放的时代，准备做什么特色功能来脱颖而出？
> 2. 有没有打算打通在线服务？
>    如果只是练手用 就当我没说

由于我本人是 macOS 用户，目前市面上支持跨平台的启动器只有 HMCL、MultiMC 等，而它们都不大令我满意，于是我打算自己写一个。目前 Epherome 在 macOS 上的启动速度已经比一些启动器要快了，但很多功能还非常不完善……
脱颖而出的功能的话，我以后可能会把在其他启动器所有用起来不爽的东西全部在 Epherome 里优化，在启动器内融合一键开服系统，通过图形化的包管理器快速在本地架一个服务器，在启动器内管理游戏设定、资源包、Mod等，甚至会出一个扩展 API 来丰富 Epherome 的功能……
2. 在线服务的话，有这个计划，后端可能会开源。

**Comment by ResetPower** [comment]
扩展 API 当然是基于 Node.js 的了（因为 Epherome 就是 Electron 写的），当然我知道 Python 的门槛比较低，所以我会想办法支持 Python 来丰富 Epherome 的扩展生态。

**Comment by eagle3236** [comment]
> 关于 UI，有没有具体的重新设计建议呢？

有的。我建议模仿官方启动器的设计，左栏列出创建的所有版本以及新建按钮，右栏布置功能区。
![image](https://user-images.githubusercontent.com/45303195/122039594-69ccf780-ce09-11eb-9be8-f4fe8ed0290d.png)

**Comment by ResetPower** [comment]
Roger that! 后续会发布一些全新的UI更改。我们这貌似7月6号放暑假，等暑假我再肝吧……我这还得准备一堆考试……

**Comment by eagle3236** [comment]
## 补充问题
启动速度需要改善

**Comment by ResetPower** [comment]
> ## 补充问题
> 启动速度需要改善

@eagle3236  请详细描述问题。如：
- 启动器打开慢还是 Minecraft 启动慢
- 使用的是什么操作系统？Epherome 版本是什么？
- ……

**Comment by eagle3236** [comment]
> > ## 补充问题
> > 启动速度需要改善
> 
> @eagle3236 请详细描述问题。如：
> 
> * 启动器打开慢还是 Minecraft 启动慢
> * 使用的是什么操作系统？Epherome 版本是什么？
> * ……

已修改

**Comment by ResetPower** [comment]
> ## 补充问题
> 启动器的启动速度需要改善
> 
> ## 测试环境
> * Windows 10 20H1 x64
> * Epherome 0.0.5

Windows 版本下由于 exe 文件是被压缩的（macOS/Linux 安装时有解压过程）因此打开启动器需要等待一段时间。
我会尽量优化，或者通过安装包模式，0.1.0 版本将会有所改善。

**Comment by Pantyhose-X** [comment]
一键开服系统，现在我用 https://github.com/cuberite/cuberite
