### ISSUE TITLE
#问题反馈#

### ISSUE THREAD

**Issue by LIPiston** [ResetPower/Epherome#21]
设定-->关于 中的minecraft下载文件夹日英显示反了

**Comment by ResetPower** [comment]
就是「设定——关于」里的这个文字

![image](https://user-images.githubusercontent.com/49084517/125808647-d7685a7f-4305-42fa-bad1-11bb812bf9f8.png)

日语和英语搞反了

---

已在最新 commit 中修复。
Fixed in the latest commit.
