### ISSUE TITLE
关于Mod控制与版本控制等

### ISSUE THREAD

**Issue by zhuaidadaya** [ResetPower/Epherome#22]
# 建议
这有一些功能建议以及解决方案

## Mod 控制
Ehperome 需要一个mod控制功能，来启用或是关闭mod
一般通过文件后缀判断是否启用，以特定后缀代表关闭
可以使用JSON来进行管理，进行起来更为方便
建议语法
```
{
    "mod1": {
        "name": "example-mod",
        "description": "This is a example",
        "website": "https://github.com/ResetPower/Epherome/issues/new",
        "version": "0.0.1 Es 1",
        "enable": true
    }
}
```

以上信息均可读取mod的jar文件后获得
在fabric，可以直接从 ROOT\fabric.mod.json 读取mod信息

> 通过id和version以及mixins判断mod
> 即便文件名被更改也不影响JSON的关联性
<hr>
但是forge中貌似并没有这样类似的文件（

## 游戏文件下载
这是最需要赶的一个功能了
游戏文件可以通过官方提供的链接或镜像下载

## 自动查找与下载java
在java默认文件夹以遍历搜索java.exe
通过java.exe位置重建java文件夹
对每个安装的java都进行次操作，即可获得正常的java路径

如果默认文件夹无java，则提示安装或者导入java.exe

同样建议以json存储java位置

**Comment by eagle3236** [comment]
不应以特定游戏后缀作为是否启用的标准。
`.jar` - 启用
`其他任意后缀，且解包后为mod格式` - 禁用

**Comment by ResetPower** [comment]
> 不应以特定游戏后缀作为是否启用的标准。
> `.jar` - 启用
> `其他任意后缀，且解包后为mod格式` - 禁用

LiteLoader 的后缀为 `.litemod`
并且我们不确定是否有其他的 Mod Loader 不以 `.jar` 为后缀的
所以我觉得可以给禁用的加上 `.disabled` 后缀，无此后缀即启用

**Comment by eagle3236** [comment]
> > 不应以特定游戏后缀作为是否启用的标准。
> > `.jar` - 启用
> > `其他任意后缀，且解包后为mod格式` - 禁用
> 
> LiteLoader 的后缀为 `.litemod`
> 并且我们不确定是否有其他的 Mod Loader 不以 `.jar` 为后缀的
> 所以我觉得可以给禁用的加上 `.disabled` 后缀，无此后缀即启用
> 以解包后格式判断也不能适应全部 Mod Loader

使用 `.disabled`无法判断用户手动修改的后缀 比如`.jar'`

**Comment by Frank-Wang-2007** [comment]
emmm，forge老版本也有类似的mcmod.info，高版本变成了一个toml文件，但是始终还是存在的

**Comment by ResetPower** [comment]
problems mentioned in this issue are solved, time to close it
