### ISSUE TITLE
几个小问题&建议

### ISSUE THREAD

**Issue by LIPiston** [ResetPower/Epherome#24]
### 人麻了
- JAVA的添加时不时会识别错误（64位识别为32位
- mojang登录有一定的不稳定性（需要我用一定的cps来点击登录）
- 登录成功后过久未启动才询问密码，不需要多次询问
- 提高一言api反应速度
- 档案和用户中右侧的文字需要优化排版
- 下载文件的日志可以放到进程管理中
- 下载文件的总进度（而不是多少个文件）
- 启动失败后弹出文本时增加自动换行以及滚动

**Comment by ResetPower** [comment]
（注：代*号代表在我电脑上没问题）
1. 请用cmd执行 java -version 看看输出*
2. *
3. *
4. 提高不了，服务器太拉垮没钱买好的
5. 能具体点吗
6. 等下载支持作为 Background Task 的时候会有的
7. 我尽量
8. 我尽量

**Comment by LIPiston** [comment]
回复
- 关于2
> 可能是mojang服务器有些不稳定，早上就没事了
- 关于3
> 在账户中登录成功后，就不需要再次登录进行游戏，如果长时间不登陆（如一个月）就需要输入一次密码。
- 关于5
> 需要有分开的样式，而不是单纯的文字，看着有点不舒服，慢慢优化

**Comment by ResetPower** [comment]
回复 @LIPiston 
- 关于 3
> 这是正常现象，如果不存储你真实密码的启动器都需要在长时间不登录后（或使用其他启动器登录后）询问密码，与 Mojang Yggdrasil API 机制有关。（可能是你用的某无良闭源启动器存了你真实密码导致没这个问题？没错我说的就是那个p开头的）
- 关于 5
> Roger that! 理解到了您的意思，我尽量优化。

**Comment by ResetPower** [comment]
问题已经基本解决，还有一些小问题我已经记住了，会在下个版本解决。
