### ISSUE TITLE
亿些“小”问题和“小”建议

### ISSUE THREAD

**Issue by Frank-Wang-2007** [ResetPower/Epherome#27]
# 版本： Epherome v0.2.3

</br>

---

</br>

## 一、添加Java时如果该Java是唯一一个已知Java路径则自动选中
![image](https://user-images.githubusercontent.com/70057967/130311911-a9b74e29-caf6-4ccc-8e12-230ef3c86612.png)

</br>

---

</br>

## 二、Linux下自动检测java路径时扫描一下/usr/lib/jvm/xxx/bin/java
***也顺便读一下/etc/profile里面的JAVA_HOME***

</br>

---

</br>

## 三、创建档案的页面，左侧按钮横向拉长居中，不要靠左（账户位置同理）
![image](https://user-images.githubusercontent.com/70057967/130311949-0b6117d2-3426-4c9b-932e-7b50ebfd5ef8.png)

</br>

---

</br>

## 四、账户页面，每个账户用一个Card来存放而不是直接渲染在背景上
![image](https://user-images.githubusercontent.com/70057967/130311988-8fa9b83a-a1da-4e1a-a7d4-8aa8dde8e604.png)

</br>

---

</br>

## 五、下载前先询问档案存储位置，~~随便往linux用户的主目录放东西会被打的~~
![image](https://user-images.githubusercontent.com/70057967/130312180-9f40eb17-dc7b-4f2c-a981-73dbf990e8dc.png)

</br>

---

</br>

## 六、下载完成时弹窗提示或自动弹回主页面/档案编辑页面
![image](https://user-images.githubusercontent.com/70057967/130312145-d47f8a4a-f3d1-496c-87f1-daa3303d92cf.png)

</br>

---

</br>

## 七、主页面边距加大
![image](https://user-images.githubusercontent.com/70057967/130312001-851abbf4-aef5-4144-b6f3-55578c7bf5d4.png)

</br>

---

</br>

~~Carbon yyds请你不要不识抬举[doge]~~

**Comment by ResetPower** [comment]
我看出来你这是 KDE 了 /斜眼笑
很快就把这些玩意改了

**Comment by ResetPower** [comment]
对于第四条：是否可以像档案的常规页一样处理？

**Comment by ResetPower** [comment]
能解决的都已在最新发行版 0.2.4 中解决了
