### ISSUE TITLE
催更

### ISSUE THREAD

**Issue by Frank-Wang-2007** [ResetPower/Epherome#3]
你给赶紧爷做微软登录[doge]，密码框那里加个大写的提示（，mojang登录的用户名应该改成邮箱（

**Comment by ResetPower** [comment]
Roger that!
将会在0.0.2中更新（

**Comment by ResetPower** [comment]
好兄弟，还是0.0.3再支持微软登录吧（

**Comment by ResetPower** [comment]
好兄弟，还是0.0.4再支持微软登录吧（
……
说实在的，微软登录确实带有很大难度，需要一段时间，虽然现在微软账户用户还是较少，但我还是尽量早点出这个功能（

**Comment by ResetPower** [comment]
最新发布的0.0.3已经支持了微软登录！！！！
