### ISSUE TITLE
Add auto java install for the latest version of Minecraft

### ISSUE THREAD

**Issue by JEijiandrei** [ResetPower/Epherome#40]
Add auto java install since I can't download java 16 on the internet and som
e of the launchers has auto java install in the launcher itself

**Comment by ResetPower** [comment]
This is one of the coming features of version 0.3.1.
I won't close the issue until it comes.

**Comment by ResetPower** [comment]
I still don't have an idea how to do it. I added a simple prototype of java install in the latest commit.
