### ISSUE TITLE
A Download Bug

### ISSUE THREAD

**Issue by mc-doge666** [ResetPower/Epherome#42]
When you have a download task in progress but not completed, click Cancel and then download again. You will find that the process and progress bar of the downloaded file is wrong.当你有一个下载任务正在进行却又没完成时，点击取消，然后重新下载。就会发现下载文件的进程和进度条错乱

**Comment by Pantyhose-X** [comment]
只下载`.jar` 就好，下完解压就行。下载1000多个文件会慢，不使用官方源也会慢。

**Comment by ResetPower** [comment]
@Pantyhose-X 可以加入我们的 QQ 群 1011896503，这边想跟您深入交流一下（友好地

**Comment by ResetPower** [comment]
fixed.
