### ISSUE TITLE
又一个下载bug  [another download bug!]

### ISSUE THREAD

**Issue by mc-doge666** [ResetPower/Epherome#48]
![image](https://user-images.githubusercontent.com/77102592/151565646-2a0b6c8a-4175-48b0-8975-9f67edf07202.png)
我不确定是不是我这里的问题，每次安装新的版本都会卡死在这里，无论是重进还是重启电脑都没有用。

**Comment by mc-doge666** [comment]
i'm not sure if it's my problem here, every time i install a new version it gets stuck here, and it doesn't matter whether it's re-entering or restarting the computer.

**Comment by JEijiandrei** [comment]
hmmm try to cancel the download and turn off then turn on your wifi i your pc then close the launcher and reopen it since this is also a problem for me but i managed to fix it by doing this method

**Comment by mc-doge666** [comment]
> 嗯，尝试取消下载并关闭，然后打开您的wifi，然后关闭启动器并重新打开它，因为这对我来说也是一个问题，但我设法通过执行此方法修复了它

这不管用的

**Comment by JEijiandrei** [comment]
new version is release and i think its fixed

**Comment by ResetPower** [comment]
yes
