### ISSUE TITLE
在未更改外观的情况下点击选项仍会要求重启

### ISSUE THREAD

**Issue by stydxm** [ResetPower/Epherome#53]
![1](https://user-images.githubusercontent.com/62790279/152720452-5b5324a8-8c72-4dd0-954a-439ade7e3802.gif)

**Comment by ResetPower** [comment]
视频看不见😨🙈

**Comment by stydxm** [comment]
> 视频看不见😨🙈

发的时候没注意，挺离谱的，重新录了重新传还是不行，转成GIF之后好了
