### ISSUE TITLE
作为库使用，生成自动化安装客户端的启动器

### ISSUE THREAD

**Issue by stydxm** [ResetPower/Epherome#59]
希望可以实现这样的效果
先命令行里
``` bash
npm init epherome
```
然后写点代码
``` javascript
let eph = require("epherome")
let minecraftClient = eph.create("1.16.5")
eph.installJava("11")
minecraftClient.installForge("latest")
minecraftClient.installModPack("https://xxxxxxx.xx/modpack.zip")
minecraftClient.enterServer("Minecraft服务器", "xx.xxxxxxxx.xx")
minecraftClient.launch()
```
再到命令行
``` bash
npm run build
```
生成二进制文件，打开后即安装java8，安装1.16.5和forge，从url下载整合包，然后自动启动并进入服务器

**Comment by ResetPower** [comment]
如果按你说的做，生成的二进制文件需要携带 Node.js 运行时，体积并不比完整的 Epherome 小。
目前有制作命令行的计划。实现方式大概是正常安装 Epherome 后去设置中开启，然后可以在命令行中使用 `eph` 命令了。

**Comment by stydxm** [comment]
> 如果按你说的做，生成的二进制文件需要携带 Node.js 运行时，体积并不比完整的 Epherome 小。 目前有制作命令行的计划。实现方式大概是正常安装 Epherome 后去设置中开启，然后可以在命令行中使用 `eph` 命令了。

当然不需要更小，而是比原来更易用，适合做服务器整合包

**Comment by ResetPower** [comment]
> > 如果按你说的做，生成的二进制文件需要携带 Node.js 运行时，体积并不比完整的 Epherome 小。 目前有制作命令行的计划。实现方式大概是正常安装 Epherome 后去设置中开启，然后可以在命令行中使用 `eph` 命令了。
> 
> 当然不需要更小，而是比原来更易用，适合做服务器或者一些新手整合包，至于命令行的话，其实意义不大，毕竟虽然启动器可以在命令行下用，mc又不能在命令行里玩

命令行有意义，可以便于自动化

**Comment by stydxm** [comment]
> > > 如果按你说的做，生成的二进制文件需要携带 Node.js 运行时，体积并不比完整的 Epherome 小。 目前有制作命令行的计划。实现方式大概是正常安装 Epherome 后去设置中开启，然后可以在命令行中使用 `eph` 命令了。
> > 
> > 
> > 当然不需要更小，而是比原来更易用，适合做服务器或者一些新手整合包，至于命令行的话，其实意义不大，毕竟虽然启动器可以在命令行下用，mc又不能在命令行里玩
> 
> 命令行有意义，可以便于自动化

MC不会频繁安装卸载，所以说需要自动化的人大概率不会用命令行，会用命令行的人不需要自动化安装游戏
