### ISSUE TITLE
麻烦优化一下Linux KDE启动速度

### ISSUE THREAD

**Issue by Frank-Wang-2007** [ResetPower/Epherome#6]
我的配置是：
OS: Arch Linux x86_64 
Kernel: 5.10.15-arch1-1 
Resolution: 1366x768 
DE: Plasma 5.20.5 
WM: KWin 
CPU: Intel i5-7200U (4) @ 3.100GHz 
GPU: NVIDIA GeForce 940MX 
GPU: Intel HD Graphics 620 
Memory: 9759MiB / 15875MiB 

arch+kde启动太慢了，要将近两分钟（

**Comment by ResetPower** [comment]
我在gnome上也是很慢，不过不到一分钟……
看看是不是Linux方面出了啥问题吧
