### ISSUE TITLE
UI上的文字能被选择

### ISSUE THREAD

**Issue by xiao-huang-ren233** [ResetPower/Epherome#73]
![5ad70236dfee9858](https://user-images.githubusercontent.com/68811840/179392043-260e1255-2a3d-4c6b-8b6a-aed2edf01ffc.jpg)
![255903f133eca2ec](https://user-images.githubusercontent.com/68811840/179392048-6d655ed1-950c-4666-ab71-658627acac16.jpg)

**Comment by ResetPower** [comment]
this is not entirely a "problem".
