### ISSUE TITLE
外观设定默认值变更

### ISSUE THREAD

**Issue by TheNightmareX** [ResetPower/Epherome#79]
以下默认值可能用户体验更佳

- 默认使用 Web-based 标题栏
- 默认主题跟随系统

另外系统标题栏真的相当不协调，可以考虑完全删除该选项

**Comment by ResetPower** [comment]
系统标题栏相当不协调是 Windows-only 的吧

**Comment by TheNightmareX** [comment]
windows用户数量相当多，即便该问题仅在windows上存在也是值得考虑的

**Comment by ResetPower** [comment]
- 默认主题跟随系统 ✔️
- Windows 默认使用 Web-based 标题栏 ✔️
