### ISSUE TITLE
Discovery of version 0.0.1

### ISSUE THREAD

**Issue by LIPiston** [ResetPower/Epherome#8]
### Discovery of version 0.0.1
1. The current javaw path needs to be filled in by yourself

**2. Unable to start the special end (such as optifine end)**

_3. The version of the file should be filled in as JSON file name_

4. Download the game

5. Identification of version isolation

6. The interface can be made more neat and beautiful

### Author's reply

1: The system environment variable Java will be detected in 0.0.2_ Path, if not detected, ask the user and prompt to download

2: Forge, Lite loader, fabric and optifine will be supported in 0.0.2

3: This may have some difficulties, and our JSON path format is < folder > / versions / < version > / < version >. JSON, and the jar path format is < folder > / versions / < version > / < version >. Jar. If so, do we have to fill in the jar file name? Is it necessary to fill in the folder name? It is a common rule of minecraft that the version folder and the JSON file name are consistent with the jar file name.

4: Support will be provided in 0.0.2 or 0.0.3

5: Support will be provided in 0.0.2

**Comment by ResetPower** [comment]
Very good!
I will resolve them in the future
hahahahahhahahahahah

**Comment by ResetPower** [comment]
Will be solved in 0.0.3
