### ISSUE TITLE
请审查启动检查流程

### ISSUE THREAD

**Issue by sophielong2002** [ResetPower/Epherome#81]
系统版本(不计入32位作业系统)
Windows 10 1809 Enterprise x64
Windows 10 1903 Enterprise x64
Windows 10 1909 Enterprise x64
Windows 10 2004 Enterprise x64
Windows 10 20H2 Enterprise x64
Windows 10 21H1 Enterprise x64
Windows 10 21H2 Enterprise x64
Windows 11 Insider Preview 21996 Enterprise x64
Windows 11 Insider Preview 22000.1 Enterprise x64
Windows 11 Insider Preview 22000.51 Enterprise x64
Windows 11 Insider Preview 22610 Enterprise x64
Windows 11 Release 22000.613 Professional x64
Windows 11 Insider Preview 25179.1000 Enterpise x64

不能正常启动
显示空白页或者报错 包含以下类型
===============
![QQ图片20220814192520](https://user-images.githubusercontent.com/93809259/184534551-565818ab-83cb-4a57-8861-418cf9ca085f.png)
![QQ图片20220814192531](https://user-images.githubusercontent.com/93809259/184534552-e56463ab-e936-4e2c-90d5-ba4f2248d5b4.jpg)
![QQ图片20220814192602](https://user-images.githubusercontent.com/93809259/184534553-5e0691c1-4448-42c3-8ab1-71e005b5ea0f.png)

**Comment by mc-doge666** [comment]
同样情况

**Comment by ResetPower** [comment]
问题已找到：
https://github.com/ResetPower/Epherome/blob/main/native/src/java/checker.rs#L35
