### ISSUE TITLE
建议（Server Control）

### ISSUE THREAD

**Issue by mc-doge666** [ResetPower/Epherome#91]
![image](https://user-images.githubusercontent.com/77102592/186050435-49bc7c31-fa05-46a8-bd0d-729d1185d82f.png)
希望能在点击玩家的同时显示更详细的信息，比如uuid，下载皮肤，这样的。也可以兼容以后开发的开服器插件，实现客户端显示玩家坐标所在维度等详细信息

**Comment by ResetPower** [comment]
👍 This is an impossible task. Thanks for your nice words.
