### ISSUE TITLE
Apple Silicon M2无法打开启动器

### ISSUE THREAD

**Issue by cuiboran** [ResetPower/Epherome#96]

**Comment by ResetPower** [comment]
请提供更多信息。

**Comment by baobao1270** [comment]
Same issue

OS: macOS 12.6
Model: MacBook Air（M2，2022年）
Version: 0.6.5, 0.6.3

Only arm64 architecture has the problem. x64 version with Rosetta works.

Screenshot is provided below:

<img width="260" alt="Snipaste_2022-10-12_18-01-47" src="https://user-images.githubusercontent.com/7949769/195477058-570e6b93-6a66-4538-803e-41ade9787e74.png">

**Comment by ResetPower** [comment]
As I know, M1 can open it normally
I can't find the reason in a short time 🤔

**Comment by ResetPower** [comment]
The problem has been solved in the latest commit.
